name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./midi_visualizer_studio
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Extract Version and Repo Name
        run: |
          echo "APP_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Build Web
        run: flutter build web --release --build-name=${{ env.APP_VERSION }} --base-href "/${{ env.REPO_NAME }}/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./midi_visualizer_studio/build/web

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./midi_visualizer_studio
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Extract Version
        shell: pwsh
        run: |
          $version = $env:GITHUB_REF -replace '^refs/tags/v', ''
          echo "APP_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build Windows
        run: flutter build windows --release --build-name=${{ env.APP_VERSION }}

      - name: Compress Artifacts
        shell: pwsh
        run: |
          Compress-Archive -Path "build\windows\x64\runner\Release\*" -DestinationPath "MIDI-Visualizer-Studio-Windows-${{ env.APP_VERSION }}.zip"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: midi_visualizer_studio/MIDI-Visualizer-Studio-Windows-${{ env.APP_VERSION }}.zip
